{
 "title": "Bitbucket Mesh Overview",
 "tags": [ "bitbucket-mesh" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "java_lang_Runtime_Pid{}", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{}/1000",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "java_lang_Runtime_StartTime{}", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Available CPU Cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Blocked Threads",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"BLOCKED\"}",
     "legendFormat": "{{ state }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "Heap Used %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(jvm_memory_bytes_used{area=\"heap\",}/jvm_memory_bytes_max{area=\"heap\",})",
     "legendFormat": "Used {{ area }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_ProcessCpuLoad{} * 100)",
     "legendFormat": "cpu load ({{ instance }})"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(java_lang_G1_Old_Generation_CollectionCount{}[10m])",
     "legendFormat": "G1_Old_Generation ({{ instance }})"
    },
    {
     "expr": "increase(java_lang_G1_Young_Generation_CollectionCount{}[10m])",
     "legendFormat": "G1_Young_Generation ({{ instance }})"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(java_lang_G1_Old_Generation_CollectionTime{}[10m])",
     "legendFormat": "G1_Old_Generation ({{ instance }})"
    },
    {
     "expr": "increase(java_lang_G1_Young_Generation_CollectionTime{}[10m])",
     "legendFormat": "G1_Young_Generation ({{ instance }})"
    }
   ]
  },
  {
   "title": "Hikari Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_zaxxer_hikari_Pool_bitbucket_mesh_IdleConnections{}",
     "legendFormat": "idle ({{ instance }})"
    },
    {
     "expr": "com_zaxxer_hikari_Pool_bitbucket_mesh_ActiveConnections{}",
     "legendFormat": "active ({{ instance }})"
    },
    {
     "expr": "com_zaxxer_hikari_Pool_bitbucket_mesh_ThreadsAwaitingConnection{}",
     "legendFormat": "awaiting ({{ instance }})"
    },
    {
     "expr": "com_zaxxer_hikari_Pool_bitbucket_mesh_TotalConnections{}",
     "legendFormat": "total ({{ instance }})"
    }
   ]
  }
 ]
}