{
 "title": "Cache clearing",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Flush All Caches Rate (cluster wide)",
   "type": "timeseries",
   "description": "Indicates that all caches are being flushed by a plugin. This is an operation which should not be triggered by external plugins and can lead to product slowdowns\n\n \n\nDetermine who invoked this, this can be determined by the invokerPluginKey tag. Reach out to the app vendor and flag this issue to them. \n\nAdditionally, the className tag refers to the implementation of CacheManager invoked and may be helpful. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(com_atlassian_confluence_metrics_Count{category00=\"cacheManager\",name=\"flushAll\"}[5m])",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Remove all entries rate (cluster wide)",
   "type": "timeseries",
   "description": "Indicates that a single cache has all of its entries removed. This may or may not cause slowdowns in products or plugins. \n\nCheck the frequency at which these cache removals occur and from which product. You can find out what plugin created the cache using the pluginKeyAtCreation tag. Additionally, the className tag refers to the implementation of Cache, which may be helpful. If the frequency is excessive, consider reaching out to the app vendor and flag this issue to them. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (tag_pluginKeyAtCreation) (rate(com_atlassian_confluence_metrics_Count{category00=\"cache\",name=\"removeAll\"}[5m]))",
     "legendFormat": "{{tag_pluginKeyAtCreation}}"
    }
   ]
  },
  {
   "title": "Plugin enabled/disabled events (cluster wide)",
   "type": "timeseries",
   "description": "Measure how many times a plugin has been disabled/enabled since uptime.\n\nSome caches are cleared when plugin is disabled/ enabled and this may have a short term performance impact. To understand what has been disabled/enabled, check the Universal Plugin Manager audit logs.\nhttps://confluence.atlassian.com/upm/viewing-installed-apps-273875714.html",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum without (instance) (com_atlassian_confluence_metrics_Count{category00=\"plugin\",name=\"counter\",category01=\"enabled\"})",
     "legendFormat": "enabled"
    },
    {
     "expr": "sum without (instance) (com_atlassian_confluence_metrics_Count{category00=\"plugin\",name=\"counter\",category01=\"disabled\"})",
     "legendFormat": "disabled"
    }
   ]
  },
  {
   "title": "Reset cache rate (cluster wide)",
   "type": "timeseries",
   "description": "Indicates that a single entry in a cache has been reset. This may or may not cause slowdowns in products or plugins. \n\nCheck the frequency at which these cache resets occur and from which product. You can find out what plugin created the cache using the pluginKeyAtCreation tag. Additionally, the className tag refers to the implementation of CacedReference, which may be helpful. If the frequency is excessive, consider reaching out to the app vendor and flag this issue to them. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (tag_pluginKeyAtCreation) (rate(com_atlassian_confluence_metrics_Count{category00=\"cachedReference\",name=\"reset\"}[5m]))",
     "legendFormat": "{{tag_pluginKeyAtCreation}}"
    }
   ]
  }
 ]
}