{
 "title": "Confluence Overview",
 "tags": [ "confluence" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Pid{product=\"confluence\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{product=\"confluence\"}/1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_StartTime{product=\"confluence\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available CPU Cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{product=\"confluence\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Recent Alerts",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(java_lang_G1_Old_Generation_CollectionTime{product=\"confluence\"}[10m])",
     "legendFormat": "G1_Old_Generation ({{instance}})"
    },
    {
     "expr": "increase(java_lang_G1_Young_Generation_CollectionTime{product=\"confluence\"}[10m])",
     "legendFormat": "G1_Young_Generation ({{instance}})"
    }
   ]
  },
  {
   "title": "Blocked Threads",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"BLOCKED\"}",
     "legendFormat": "{{ state }} ({{instance}})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_ProcessCpuLoad{product=\"confluence\"} * 100)",
     "legendFormat": "cpu load ({{instance}})"
    }
   ]
  },
  {
   "title": "Heap Used %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(jvm_memory_bytes_used{area=\"heap\",product=\"confluence\"}/jvm_memory_bytes_max{area=\"heap\",product=\"confluence\"})",
     "legendFormat": "Used {{ area }} ({{instance}})"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_confluence_metrics_Mean{category00=\"jvm\", category01=\"gc\", product=\"confluence\"}",
     "legendFormat": "{{instance}} - {{tag_cause}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(java_lang_G1_Old_Generation_CollectionCount{product=\"confluence\"}[10m])",
     "legendFormat": "G1_Old_Generation ({{instance}})"
    },
    {
     "expr": "increase(java_lang_G1_Young_Generation_CollectionCount{product=\"confluence\"}[10m])",
     "legendFormat": "G1_Young_Generation ({{instance}})"
    }
   ]
  },
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tomcat Request Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(Standalone_GlobalRequestProcessor_requestCount{}[10m])",
     "legendFormat": "{{name}} count ({{instance}})"
    },
    {
     "expr": "increase(Standalone_GlobalRequestProcessor_errorCount{}[10m])",
     "legendFormat": "{{name}} error ({{instance}})"
    }
   ]
  },
  {
   "title": "Tomcat Threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(Standalone_ThreadPool_currentThreadCount{} / Standalone_ThreadPool_maxThreads{}) * 100",
     "legendFormat": "used {{name}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Tomcat Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(Standalone_GlobalRequestProcessor_processingTime{}[10m]) / increase(Standalone_GlobalRequestProcessor_requestCount{}[10m])",
     "legendFormat": "{{name}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Tomcat Sessions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Standalone_Manager_activeSessions{}",
     "legendFormat": "active sessions: {{context}} ({{instance}})"
    },
    {
     "expr": "Standalone_Manager_rejectedSessions{}",
     "legendFormat": "rejected sessions: {{context}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database Latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_confluence_metrics_Mean{category00=\"db\",category01=\"connection\",category02=\"latency\",name=\"statistics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reads / Writes",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(com_atlassian_confluence_metrics_Count{category00=\"postgres\",name=\"reads\"}[10m])",
     "legendFormat": "reads ({{instance}})"
    },
    {
     "expr": "rate(com_atlassian_confluence_metrics_Count{category00=\"postgres\",name=\"writes\"}[10m])",
     "legendFormat": "writes ({{instance}})"
    }
   ]
  },
  {
   "title": "Connection Pool Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(com_mchange_v2_c3p0_PooledDataSource_numBusyConnections{} / com_mchange_v2_c3p0_PooledDataSource_maxPoolSize{}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_mchange_v2_c3p0_PooledDataSource_numBusyConnections{}",
     "legendFormat": "active {{instance}}"
    },
    {
     "expr": "com_mchange_v2_c3p0_PooledDataSource_numIdleConnections{}",
     "legendFormat": "idle {{instance}}"
    }
   ]
  }
 ]
}