{
 "title": "Plugin Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Confluence Search Mean",
   "type": "timeseries",
   "description": "Measures how long a confluence search will take to return a result.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, (sum without (instance) (com_atlassian_confluence_metrics_Mean{category00=\"search\", name=\"manager\"}) / sum without (instance) (com_atlassian_confluence_metrics_Count{category00=\"search\", name=\"manager\"})*1000))",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Confluence Search p99",
   "type": "timeseries",
   "description": "Measures how long a confluence search will take to return a result.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, (com_atlassian_confluence_metrics_99thPercentile{category00=\"search\", name=\"manager\"}))",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Confluence Index Mean",
   "type": "timeseries",
   "description": "Measures how long a confluence takes to reindex\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(5, (sum without (instance) (com_atlassian_confluence_metrics_Mean{category00=\"index\", name=\"reindex\"}) / sum without (instance) (com_atlassian_confluence_metrics_Count{category00=\"index\", name=\"reindex\"})*1000))",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Confluence Index p99",
   "type": "timeseries",
   "description": "Measures how long a confluence takes to reindex\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(5, (com_atlassian_confluence_metrics_99thPercentile{category00=\"index\", name=\"reindex\"}))",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Confluence Long Running Tasks Mean",
   "type": "timeseries",
   "description": "Measures how long a confluence LongRunningTask takes to complete\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk(5, (sum without (instance) (com_atlassian_confluence_metrics_Mean{name=\"longRunningTask\"}) / sum without (instance) (com_atlassian_confluence_metrics_Count{name=\"longRunningTask\"})*1000))",
     "legendFormat": "{{tag_taskClass}}"
    }
   ]
  },
  {
   "title": "Confluence Long Running Task p99",
   "type": "timeseries",
   "description": "Measures how long a confluence Long Running Task takes to complete\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "topk(5, (com_atlassian_confluence_metrics_99thPercentile{name=\"longRunningTask\"}))",
     "legendFormat": "{{tag_taskClass}}"
    }
   ]
  }
 ]
}