---
startDelaySeconds: 0

rules:
- pattern: '(java.lang)<type=(\w+)><>(\w+):'
  name: java_lang_$2_$3
  labels:
    product: "confluence"
- pattern: 'java.lang<type=Memory><HeapMemoryUsage>(\w+)'
  name: java_lang_Memory_HeapMemoryUsage_$1
  labels:
    product: "confluence"
- pattern: 'java.lang<name=G1 (\w+) Generation, type=GarbageCollector><>(\w+)'
  name: java_lang_G1_$1_Generation_$2
  labels:
    product: "confluence"
- pattern: '.*'
