{
 "title": "Confluence Plugin Monitoring",
 "tags": [ "confluence" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Confluence Search Response Times (mean - per node)",
   "type": "timeseries",
   "description": "Measures how long a confluence search will take to return a result.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, (sum without (instance) (com_atlassian_confluence_metrics_Mean{category00=\"search\", name=\"manager\"}) / sum without (instance) (com_atlassian_confluence_metrics_Count{category00=\"search\", name=\"manager\"})*1000))",
     "legendFormat": "{{ instance }} {{tag_invokerPluginKey}} {{tag_searchType}}"
    }
   ]
  },
  {
   "title": "Confluence Search Response Times (p99 - per node)",
   "type": "timeseries",
   "description": "Measures how long a confluence search will take to return a result.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, (com_atlassian_confluence_metrics_99thPercentile{category00=\"search\", name=\"manager\"}))",
     "legendFormat": "{{ instance }} {{tag_invokerPluginKey}} {{tag_searchType}}"
    }
   ]
  },
  {
   "title": "Confluence Index Times (top 5 - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long a confluence takes to reindex\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, (sum without (instance) (com_atlassian_confluence_metrics_Mean{category00=\"index\", name=\"reindex\"}) / sum without (instance) (com_atlassian_confluence_metrics_Count{category00=\"index\", name=\"reindex\"})*1000))",
     "legendFormat": "{{ instance }} {{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Confluence Index Time (p99 - cluster wide) ",
   "type": "timeseries",
   "description": "Measures how long a confluence takes to reindex\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, (com_atlassian_confluence_metrics_99thPercentile{category00=\"index\", name=\"reindex\"}))",
     "legendFormat": "{{ instance }} {{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Confluence Long Running Tasks Time (mean - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long a confluence LongRunningTask takes to complete\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, (sum without (instance) (com_atlassian_confluence_metrics_Mean{name=\"longRunningTask\"}) / sum without (instance) (com_atlassian_confluence_metrics_Count{name=\"longRunningTask\"})*1000))",
     "legendFormat": "{{ instance }} {{tag_taskClass}}"
    }
   ]
  },
  {
   "title": "Confluence Long Running Task Time (p99 - per node)",
   "type": "timeseries",
   "description": "Measures how long a confluence Long Running Task takes to complete\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, (com_atlassian_confluence_metrics_99thPercentile{name=\"longRunningTask\"}))",
     "legendFormat": "{{ instance }} {{tag_taskClass}}"
    }
   ]
  }
 ]
}