{
 "title": "Bamboo Overview",
 "tags": [ "bamboo" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Pid{product=\"bamboo\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{product=\"bamboo\"}/1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_StartTime{product=\"bamboo\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available CPU Cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{product=\"bamboo\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocked Threads",
   "type": "gauge",
   "gridPos": { "h": 19, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"BLOCKED\"}",
     "legendFormat": "{{ state }} ({{instance}})"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(java_lang_G1_Old_Generation_CollectionTime{product=\"bamboo\"}[10m])",
     "legendFormat": "G1_Old_Generation ({{instance}})"
    },
    {
     "expr": "increase(java_lang_G1_Young_Generation_CollectionTime{product=\"bamboo\"}[10m])",
     "legendFormat": "G1_Young_Generation ({{instance}})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_ProcessCpuLoad{product=\"bamboo\"} * 100)",
     "legendFormat": "cpu load ({{instance}})"
    }
   ]
  },
  {
   "title": "Heap Used %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(jvm_memory_bytes_used{area=\"heap\"}/jvm_memory_bytes_max{area=\"heap\"})",
     "legendFormat": "Used {{ area }} ({{instance}})"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(java_lang_G1_Old_Generation_CollectionCount{product=\"bamboo\"}[10m])",
     "legendFormat": "G1_Old_Generation ({{instance}})"
    },
    {
     "expr": "increase(java_lang_G1_Young_Generation_CollectionCount{product=\"bamboo\"}[10m])",
     "legendFormat": "G1_Young_Generation ({{instance}})"
    }
   ]
  },
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tomcat Request Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_requestCount{}[10m])",
     "legendFormat": "{{name}} count ({{instance}})"
    },
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_errorCount{}[10m])",
     "legendFormat": "{{name}} error ({{instance}})"
    }
   ]
  },
  {
   "title": "Tomcat Threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(Catalina_ThreadPool_currentThreadCount{} / Catalina_ThreadPool_maxThreads{}) * 100",
     "legendFormat": "used {{name}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Tomcat Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_processingTime{}[10m]) / increase(Catalina_GlobalRequestProcessor_requestCount{}[10m])",
     "legendFormat": "{{name}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Tomcat Sessions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Catalina_Manager_activeSessions{}",
     "legendFormat": "active sessions: {{context}} ({{instance}})"
    },
    {
     "expr": "Catalina_Manager_rejectedSessions{}",
     "legendFormat": "rejected sessions: {{context}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total and Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "com_zaxxer_hikari_Pool_HikariPool_2_ActiveConnections",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_zaxxer_hikari_Pool_HikariPool_2_TotalConnections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads awaiting connection",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_zaxxer_hikari_Pool_HikariPool_2_ThreadsAwaitingConnection",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_zaxxer_hikari_Pool_HikariPool_2_IdleConnections",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}