{
 "title": "Bitbucket Git Operations",
 "tags": [ "bitbucket" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Clone request count",
   "type": "timeseries",
   "description": "Number of clone requests served over HTTP and SSH",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_CloneRequestCount{}[5m])",
     "legendFormat": "{{name}} HTTP ({{ instance }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_CloneRequestCount{}[5m])",
     "legendFormat": "{{name}} SSH ({{ instance }})"
    }
   ]
  },
  {
   "title": "Cloned bytes read & written to clients ",
   "type": "timeseries",
   "description": "Bytes read from clients during clone operations",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_CloneBytesRead{}[5m])",
     "legendFormat": "{{name}} HTTP bytes read ({{ instance }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_CloneBytesRead{}[5m])",
     "legendFormat": "{{name}} SSH bytes read ({{ instance }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_CloneBytesWritten{}[5m])",
     "legendFormat": "{{name}} HTTP bytes written ({{ instance }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_CloneBytesWritten{}[5m])",
     "legendFormat": "{{name}} SSH bytes written ({{ instance }})"
    }
   ]
  },
  {
   "title": "Total number of requests served",
   "type": "timeseries",
   "description": "Total number of requests served",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_RequestCount{}[5m])",
     "legendFormat": "{{name}} HTTP ({{ instance }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_RequestCount{}[5m])",
     "legendFormat": "{{name}} SSH ({{ instance }})"
    }
   ]
  },
  {
   "title": "Total bytes read & written to clients",
   "type": "timeseries",
   "description": "Total bytes read and written",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_TotalBytesRead{}[5m])",
     "legendFormat": "HTTP bytes read ({{instance}})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_TotalBytesRead{}[5m])",
     "legendFormat": "SSH bytes read ({{instance}})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_TotalBytesWritten{}[5m])",
     "legendFormat": "HTTP bytes written ({{instance}})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_TotalBytesWritten{}[5m])",
     "legendFormat": "SSH bytes written ({{instance}})"
    }
   ]
  },
  {
   "title": "Clone cache hit, miss & bypass count",
   "type": "timeseries",
   "description": "HTTP and SSH Clone requests that could not be served from the scm-cache",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_CloneCacheMiss{}[5m])",
     "legendFormat": "{{name}} HTTP miss ({{ instance }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_CloneCacheMiss{}[5m])",
     "legendFormat": "{{name}} SSH miss ({{ instance }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_CloneCacheHit{}[5m])",
     "legendFormat": "{{name}} HTTP hit ({{ instance }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_CloneCacheHit{}[5m])",
     "legendFormat": "{{name}} SSH hit ({{ instance }})"
    },
    {
     "expr": "com_atlassian_bitbucket_HttpHostingStatistics_CloneCacheBypass",
     "legendFormat": "{{name}} HTTP bypass ({{ instance }})"
    },
    {
     "expr": "com_atlassian_bitbucket_SshHostingStatistics_CloneCacheBypass",
     "legendFormat": "{{name}} SSH bypass ({{ instance }})"
    }
   ]
  },
  {
   "title": "Fetch request count",
   "type": "timeseries",
   "description": "Number of fetch requests served\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_FetchRequestCount{}[5m])",
     "legendFormat": "{{name}} HTTP ({{ instance }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_FetchRequestCount{}[5m])",
     "legendFormat": "{{name}} SSH ({{ instance }})"
    }
   ]
  },
  {
   "title": "Fetched bytes read and written to clients",
   "type": "timeseries",
   "description": "Bytes read and written from clients during fetch operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_FetchBytesRead{}[5m])",
     "legendFormat": "{{name}} HTTP bytes read ({{ instance }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_FetchBytesRead{}[5m])",
     "legendFormat": "{{name}} SSH bytes read ({{ instance }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_FetchBytesWritten{}[5m])",
     "legendFormat": "{{name}} HTTP bytes written ({{ instance }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_FetchBytesWritten{}[5m])",
     "legendFormat": "{{name}} SSH bytes written ({{ instance }})"
    }
   ]
  }
 ]
}