{
 "title": "Bitbucket Mesh gRPC",
 "tags": [ "bitbucket" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_grpc_Value{section=\"calls\",name=\"total\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Running Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_grpc_Value{section=\"calls\",name=\"running\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Successful Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_grpc_Value{section=\"calls\",name=\"successful\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_grpc_Value{section=\"calls\",name=\"failed\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MemoryPool Bytes Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "metrics_grpc_Value{section=\"memoryPool\", name=\"used\"}",
     "legendFormat": "{{name}} ({{ instance }})"
    }
   ]
  },
  {
   "title": "Number of Thread Caches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_grpc_Value{section=\"memoryPool\", name=\"numThreadCaches\"}",
     "legendFormat": "{{name}} ({{ instance }})"
    }
   ]
  }
 ]
}