{
 "title": "Bitbucket NIO pump thread pool stats",
 "description": "Details relating to Threads that handle nonblocking process I/O",
 "tags": [ "bitbucket" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current pool size",
   "type": "timeseries",
   "description": "The current number of threads in the pool",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_thread_pools_NioPumpThreadPool_PoolSize{}[5m])",
     "legendFormat": "{{name}} Current thread count ({{ instance }})"
    }
   ]
  },
  {
   "title": "Active thread count",
   "type": "timeseries",
   "description": "The approximate number of threads that are actively executing tasks",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_thread_pools_NioPumpThreadPool_ActiveCount{}[5m])",
     "legendFormat": "{{name}} Active threads ({{ instance }})"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "timeseries",
   "description": "The number of tasks awaiting execution by the thread pool",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_thread_pools_NioPumpThreadPool_QueueLength{}[5m])",
     "legendFormat": "{{name}} Current queue length ({{ instance }})"
    }
   ]
  },
  {
   "title": "Completed task count",
   "type": "timeseries",
   "description": "The approximate total number of tasks that have completed execution. Because the states of tasks and threads may change dynamically during computation, the returned value is only an approximation, but one that does not ever decrease across successive calls",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_thread_pools_NioPumpThreadPool_CompletedTaskCount{}[5m])",
     "legendFormat": "{{name}} Completed tasks ({{ instance }})"
    }
   ]
  },
  {
   "title": "Largest pool size",
   "type": "timeseries",
   "description": "The largest number of threads that have ever been simultaneously in the pool",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_thread_pools_NioPumpThreadPool_LargestPoolSize{}[5m])",
     "legendFormat": "{{name}} Largest thread count ({{ instance }})"
    }
   ]
  },
  {
   "title": "Max pool size",
   "type": "timeseries",
   "description": "The maximum allowed number of threads",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_thread_pools_NioPumpThreadPool_MaximumPoolSize{}[5m])",
     "legendFormat": "{{name}} Max pool size ({{ instance }})"
    }
   ]
  }
 ]
}