{
 "title": "Bitbucket SSH statistics",
 "description": "Bitbucket uses 'tickets' as a mechanism for creating back-pressure to prevent the system from being overloaded with requests. There are two types of tickets, hosting tickets and command tickets. ",
 "tags": [ "bitbucket" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active session count",
   "type": "timeseries",
   "description": "Number of currently active SSH session",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_SshSessions_ActiveSessionCount{}[5m])",
     "legendFormat": "{{name}} Active session count ({{ instance }})"
    }
   ]
  },
  {
   "title": "Max active session count",
   "type": "timeseries",
   "description": "Highest number of concurrently active SSH sessions since the last startup",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_SshSessions_MaxActiveSessionCount{}[5m])",
     "legendFormat": "{{name}} Max session count ({{ instance }})"
    }
   ]
  },
  {
   "title": "Session created count",
   "type": "timeseries",
   "description": "Total number of SSH sessions that have been created since the last startup",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_SshSessions_SessionCreatedCount{}[5m])",
     "legendFormat": "{{name}} Session created count ({{ instance }})"
    }
   ]
  },
  {
   "title": "Session closed count",
   "type": "timeseries",
   "description": "Total number of SSH sessions that have been closed since the last startup\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_SshSessions_SessionClosedCount{}[5m])",
     "legendFormat": "{{name}} Session closed count ({{ instance }})"
    }
   ]
  },
  {
   "title": "Session exception count",
   "type": "timeseries",
   "description": "Total number of SSH sessions that have been terminated because an exception was thrown from the SSH command run\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_SshSessions_SessionExceptionCount{}[5m])",
     "legendFormat": "{{name}} Session exception count ({{ instance }})"
    }
   ]
  }
 ]
}