{
 "title": "Bitbucket Webhooks stats",
 "description": "Details relating to Webhooks stats",
 "tags": [ "bitbucket" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Publish count",
   "type": "timeseries",
   "description": "A count of the total number of events that could trigger webhooks\n(A publish may create many dispatches)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_PublishCount{}[5m])",
     "legendFormat": "{{name}} Publish count ({{ instance }})"
    }
   ]
  },
  {
   "title": "Dispatch success count",
   "type": "timeseries",
   "description": "Total number of webhooks to fire successfully with a successful HTTP response(A publish may create many dispatches)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_DispatchSuccessCount{}[5m])",
     "legendFormat": "{{name}} Success count ({{ instance }})"
    }
   ]
  },
  {
   "title": "Dispatch rejected count",
   "type": "timeseries",
   "description": "A count of the number of webhook dispatches that were rejected for execution",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_DispatchRejectedCount{}[5m])",
     "legendFormat": "{{name}} Rejected count ({{ instance }})"
    }
   ]
  },
  {
   "title": "Dispatch last rejected timestamp",
   "type": "timeseries",
   "description": "The last time a webhook was rejected, either from circuit breaking, or due to too many webhooks being in flight",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_DispatchLastRejectedTimestamp{}[5m])",
     "legendFormat": "{{name}} Last rejection ({{ instance }})"
    }
   ]
  },
  {
   "title": "Dispatch in-flight count",
   "type": "timeseries",
   "description": "Total number of dispatches that have been triggered and are awaiting resolution",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_DispatchInFlightCount{}[5m])",
     "legendFormat": "{{name}} In-flight count ({{ instance }})"
    }
   ]
  },
  {
   "title": "Dispatch failure count",
   "type": "timeseries",
   "description": "Total number of webhooks that fired successfully, but the HTTP response indicates a failure\n(non 2xx code)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_DispatchFailureCount{}[5m])",
     "legendFormat": "{{name}} Failure count ({{ instance }})"
    }
   ]
  },
  {
   "title": "Dispatch error count",
   "type": "timeseries",
   "description": "Total number of webhooks to have had an error while they were being dispatched(non 2xx code)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_DispatchErrorCount{}[5m])",
     "legendFormat": "{{name}} Error count ({{ instance }})"
    }
   ]
  },
  {
   "title": "Dispatch count",
   "type": "timeseries",
   "description": "Total number of webhooks to have been dispatched",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_DispatchCount{}[5m])",
     "legendFormat": "{{name}} Dispatch count ({{ instance }})"
    }
   ]
  }
 ]
}