{
 "title": "Jira General",
 "tags": [ "jira" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "java_lang_Runtime_StartTime{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Recent Alerts",
   "type": "alertlist",
   "gridPos": { "h": 11, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{}[5m])",
     "legendFormat": "{{gc}} - {{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_ProcessCpuLoad{} * 1000)",
     "legendFormat": "cpu load - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Used %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(jvm_memory_bytes_used{area=\"heap\"}/jvm_memory_bytes_max{area=\"heap\"})",
     "legendFormat": "Used {{ area }} - {{instance}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{}[5m])",
     "legendFormat": "{{gc}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Blocked Threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"BLOCKED\"}",
     "legendFormat": "{{ instance }} {{ state }}"
    }
   ]
  },
  { "title": "Tomcat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Tomcat Threads",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( Catalina_ThreadPool_currentThreadCount{} / Catalina_ThreadPool_maxThreads{}) * 100",
     "legendFormat": "used - {{instance}} ({{name}})"
    }
   ]
  },
  {
   "title": "Tomcat Request Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_requestCount{}[5m])",
     "legendFormat": "{{name}} count - {{instance}}"
    }
   ]
  },
  {
   "title": "Tomcat Error Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_errorCount{}[5m])",
     "legendFormat": "{{name}} error - {{instance}}"
    }
   ]
  },
  {
   "title": "Tomcat Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_processingTime{}[10m]) / increase(Catalina_GlobalRequestProcessor_requestCount{}[10m])",
     "legendFormat": "{{name}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Tomcat Sessions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Catalina_Manager_activeSessions{}",
     "legendFormat": "active sessions: {{instance}}"
    },
    {
     "expr": "Catalina_Manager_rejectedSessions{}",
     "legendFormat": "rejected sessions: {{instance}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Connection Pool Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(com_atlassian_jira_BasicDataSource_NumActive{connectionpool=\"connections\"} / com_atlassian_jira_BasicDataSource_MaxTotal{connectionpool=\"connections\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_atlassian_jira_BasicDataSource_NumActive{connectionpool=\"connections\"}",
     "legendFormat": "active - {{instance}}"
    },
    {
     "expr": "com_atlassian_jira_BasicDataSource_NumIdle{connectionpool=\"connections\"}",
     "legendFormat": "idle - {{instance}}"
    }
   ]
  },
  {
   "title": "Reads / Writes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(com_atlassian_jira_db_reads_invocation_count{}[5m])",
     "legendFormat": "reads - {{instance}}"
    },
    {
     "expr": "delta(com_atlassian_jira_db_writes_invocation_count{}[5m])",
     "legendFormat": "writes - {{instance}}"
    }
   ]
  },
  {
   "title": "Database Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_jira_metrics_Mean{category00=\"db\", category01=\"connection\", category02=\"latency\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}