{
 "title": "Jira Indexing",
 "tags": [ "jira" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Issue indexing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Issue Reindex (mean last 5 minutes - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long it takes for an Issue to be reindexed across the cluster\n\nIf a plugin triggers Issue reindexing that are abnormal in quantity or duration then contact the app vendor to investigate. You can find out which plugin is responsible for the Issue reindexing using the invokerPluginKey tag.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_entityType) ((com_atlassian_jira_metrics_Mean{name=\"ReIndex\", category00=\"issue\"}) * \n(delta(com_atlassian_jira_metrics_Count{name=\"ReIndex\", category00=\"issue\"}[5m])))) /\n(sum without (instance, tag_entityType) (delta(com_atlassian_jira_metrics_Count{name=\"ReIndex\", category00=\"issue\"}[5m])))\n",
     "legendFormat": "ReIndex operation"
    }
   ]
  },
  {
   "title": "Comment Reindexing by Plugin (mean last 5 minutes - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long it takes for a Comment to be reindexed by a plugin.\n\n\t\nIf a plugin triggers Comment reindexing that are abnormal in quantity or duration then contact the app vendor to investigate. You can find out which plugin is responsible for the Comment reindexing using the invokerPluginKey tag.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_entityType) ((com_atlassian_jira_metrics_Mean{category00=\"comment\", name=\"reindexing\"}) * \n(delta(com_atlassian_jira_metrics_Count{category00=\"comment\", name=\"reindexing\"}[5m])))) /\n(sum without (instance, tag_entityType) (delta(com_atlassian_jira_metrics_Count{category00=\"comment\", name=\"reindexing\"}[5m])))",
     "legendFormat": " {{ instance }} {{ tag_invokerPluginKey }}"
    }
   ]
  },
  {
   "title": "Issue Reindexing by Plugin (mean last 5 minutes - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long it takes on average for Issues to be reindexed across the cluster.\n\nIf a plugin triggers Issue reindexing that are abnormal in quantity or duration then contact the app vendor to investigate. You can find out which plugin is responsible for the Issue reindexing using the invokerPluginKey tag.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_entityType) ((com_atlassian_jira_metrics_Mean{name=\"reindexing\", category00=\"issue\"}) * \n(delta(com_atlassian_jira_metrics_Count{name=\"reindexing\", category00=\"issue\"}[5m])))) /\n(sum without (instance, tag_entityType) (delta(com_atlassian_jira_metrics_Count{name=\"reindexing\", category00=\"issue\"}[5m])))",
     "legendFormat": " {{ instance }} {{ tag_invokerPluginKey }}"
    }
   ]
  },
  {
   "title": "Comment Reindexing by Plugin (p99 - per node)",
   "type": "timeseries",
   "description": "Measures how long it takes for a Comment to be reindexed by a plugin.\n\n\t\nIf a plugin triggers Comment reindexing that are abnormal in quantity or duration then contact the app vendor to investigate. You can find out which plugin is responsible for the Comment reindexing using the invokerPluginKey tag.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_jira_metrics_99thPercentile{category00=\"comment\", name=\"reindexing\"}",
     "legendFormat": " {{ instance }} {{ tag_invokerPluginKey }}"
    }
   ]
  },
  {
   "title": "Comment Reindexing by Plugin (count - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long it takes for a Comment to be reindexed by a plugin.\n\n\t\nIf a plugin triggers Comment reindexing that are abnormal in quantity or duration then contact the app vendor to investigate. You can find out which plugin is responsible for the Comment reindexing using the invokerPluginKey tag.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg without (instance) (com_atlassian_jira_metrics_Count{category00=\"comment\", name=\"reindexing\"})",
     "legendFormat": " {{ instance }} {{ tag_invokerPluginKey }}"
    }
   ]
  },
  {
   "title": "Issue Reindexing by Plugin (p99 - per node)",
   "type": "timeseries",
   "description": "Measures how long it takes for an Issue to be reindexed per node\n\nIf a plugin triggers Issue reindexing that are abnormal in quantity or duration then contact the app vendor to investigate. You can find out which plugin is responsible for the Issue reindexing using the invokerPluginKey tag.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_jira_metrics_99thPercentile{category00=\"issue\", name=\"reindexing\"}",
     "legendFormat": " {{ instance }} {{ tag_invokerPluginKey }}"
    }
   ]
  },
  {
   "title": "Issue Reindexing by Plugin (count - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long it takes for an Issue to be reindexed across the cluster\n\nIf a plugin triggers Issue reindexing that are abnormal in quantity or duration then contact the app vendor to investigate. You can find out which plugin is responsible for the Issue reindexing using the invokerPluginKey tag.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (instance) (com_atlassian_jira_metrics_Count{category00=\"issue\", name=\"reindexing\"})",
     "legendFormat": " {{ instance }} {{ tag_invokerPluginKey }}"
    }
   ]
  },
  {
   "title": "Active Comment Reindexing Operations - (cluster wide)",
   "type": "gauge",
   "description": "Shows how many Comment operations are currently active.\n\nIf a plugin triggers Comment reindexing that are abnormal in quantity or duration then contact the app vendor to investigate. You can find out which plugin is responsible for the Comment reindexing using the invokerPluginKey tag.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, tag_invokerPluginKey) (com_atlassian_jira_metrics_Value{category00=\"comment\", name=\"reindexing\", tag_statistic=\"active\"})"
    }
   ]
  },
  {
   "title": "Active Issue Reindexing Operations - (cluster wide)",
   "type": "gauge",
   "description": "Shows how many Issue operations are currently active.\n\nIf a plugin triggers Comment reindexing that are abnormal in quantity or duration then contact the app vendor to investigate. You can find out which plugin is responsible for the Comment reindexing using the invokerPluginKey tag.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, tag_invokerPluginKey) (com_atlassian_jira_metrics_Value{category00=\"issue\", name=\"reindexing\", tag_statistic=\"active\"})"
    }
   ]
  },
  { "title": "Custom fields indexing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Custom fields indexing times (cluster-wide)",
   "type": "table",
   "description": "Measures how long custom field indexing takes and it's impact on indexing in general. High indexing times means the plugin has introduced a field that is impacting the performance of Jira and should be investigated.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "avg without (instance) (com_atlassian_jira_metrics_Mean{name=\"addIndex\", category01=\"field\"})\n\n"
    },
    {
     "expr": "max without (instance) (com_atlassian_jira_metrics_99thPercentile{name=\"addIndex\", category01=\"field\"})"
    }
   ]
  },
  {
   "title": "Custom field indexing time (mean last 5 minutes - cluster wide) ",
   "type": "timeseries",
   "description": "Measures how long custom field indexing takes and it's impact on indexing in general. High indexing times means the plugin has introduced a field that is impacting the performance of Jira and should be investigated.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance) ((com_atlassian_jira_metrics_Mean{name=\"addIndex\", category01=\"field\"}) * \n(delta(com_atlassian_jira_metrics_Count{name=\"addIndex\", category01=\"field\"}[5m])))) /\n(sum without (instance) (delta(com_atlassian_jira_metrics_Count{name=\"addIndex\", category01=\"field\"}[5m])))",
     "legendFormat": " {{ instance }} - {{tag_fromPluginKey}} - {{tag_fieldId}} "
    }
   ]
  },
  {
   "title": "Custom field total indexing time by plugin (cluster wide)",
   "type": "timeseries",
   "description": "Measures the total accumulated indexing time per plugin by summing all the custom fields indexing metrics. \n\nHigh indexing time needs to be investigated and flagged to the app vendor.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (tag_fromPluginKey) (com_atlassian_jira_metrics_Mean{name=\"addIndex\", category01=\"field\"}) + sum by (tag_fromPluginKey) (com_atlassian_jira_metrics_Mean{name=\"isFieldIndexableForIssue\", category01=\"field\"})",
     "legendFormat": " {{ instance }} {{tag_fromPluginKey}}"
    }
   ]
  }
 ]
}