{
 "title": "Jira Response Times",
 "tags": [ "jira" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Search (backed by Lucene) evaluation times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Search load - (cluster wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\nsum without (instance) ((com_atlassian_jira_metrics_Mean{category00=\"search\",name=\"index\"}) * \n(delta(com_atlassian_jira_metrics_Count{category00=\"search\",name=\"index\"}[5m])))",
     "legendFormat": "{{ instance }} {{ tag_invokerPluginKey }}"
    }
   ]
  },
  {
   "title": "Search evaluations (cluster-wide)",
   "type": "table",
   "description": "Measures how long it takes for a Lucene index search to take place. \n\nIf a plugin triggers searches that are abnormal in quantity or duration then contact the app vendor to investigate. You can find out which plugin is responsible for the index searches using the invokerPluginKey tag ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg without (instance, tag_query, category00) (com_atlassian_jira_metrics_Mean{category00=\"search\", name=\"index\"})"
    },
    {
     "expr": "sum without (instance, tag_query, category00) (com_atlassian_jira_metrics_Count{category00=\"search\", name=\"index\"})"
    },
    {
     "expr": "max without (instance, tag_query, category00) (com_atlassian_jira_metrics_99thPercentile{category00=\"search\", name=\"index\"})"
    }
   ]
  },
  {
   "title": "Searches count (last 5 minutes - cluster wide)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum without (instance) (increase(com_atlassian_jira_metrics_Count{category00=\"search\", name=\"index\"}[5m]))",
     "legendFormat": "{{ instance }} {{ tag_invokerPluginKey }}"
    }
   ]
  },
  {
   "title": "Search evaluation times (p99 - per node)",
   "type": "timeseries",
   "description": "Measures how long it takes for a Lucene index search to take place. \n\nIf a plugin triggers searches that are abnormal in quantity or duration then contact the app vendor to investigate. You can find out which plugin is responsible for the index searches using the invokerPluginKey tag ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_jira_metrics_99thPercentile{category00=\"search\", name=\"index\"}",
     "legendFormat": "{{ instance }} {{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Web fragment condition evaluation times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Web fragment condition evaluation time (mean - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long web fragment condition will take to determine whether a web fragment should be displayed or not.\n\nWeb fragments conditions determine whether a link or a section on a page should be displayed. Slow web fragment conditions lead to slow page load times especially if they are not cached. Reach out to the app vendor responsible to flag and investigate. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance) ((com_atlassian_jira_metrics_Mean{category00=\"web\", category01=\"fragment\", name=\"condition\"}) * \n(delta(com_atlassian_jira_metrics_Count{category00=\"web\", category01=\"fragment\", name=\"condition\"}[5m])))) /\n(sum without (instance) (delta(com_atlassian_jira_metrics_Count{category00=\"web\", category01=\"fragment\", name=\"condition\"}[5m])))",
     "legendFormat": "{{ instance }} {{tag_fromPluginKey}} - {{tag_conditionClassName}} (condition)"
    }
   ]
  },
  {
   "title": "Web fragment condition evaluation time (p99 - per node)",
   "type": "timeseries",
   "description": "Measures how long web fragment condition will take to determine whether a web fragment should be displayed or not.\n\nWeb fragments conditions determine whether a link or a section on a page should be displayed. Slow web fragment conditions lead to slow page load times especially if they are not cached. Reach out to the app vendor responsible to flag and investigate. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_jira_metrics_99thPercentile{category00=\"web\", category01=\"fragment\", name=\"condition\"}",
     "legendFormat": "{{ instance }} {{tag_fromPluginKey}} - {{tag_conditionClassName}} (condition)"
    }
   ]
  },
  { "title": "Soy web panel render times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Soy web panel render times (cluster-wide)",
   "type": "table",
   "description": "Measures how long a Soy Template web panel is taking to render.\n\nThe template renderer might be long-running. If there is a plugin with a slow Soy renderer it might be worth adding (tag__templateName) to the query and contacting the vendor responsible to investigate if long-running queries are expected.",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg without (instance, tag_templateName) (com_atlassian_jira_metrics_Mean{name=\"webTemplateRenderer\",tag_templateRenderer=\"soy\"})"
    },
    {
     "expr": "sum without (instance, tag_templateName) (com_atlassian_jira_metrics_Count{name=\"webTemplateRenderer\",tag_templateRenderer=\"soy\"})"
    },
    {
     "expr": "max without (instance, tag_templateName) (com_atlassian_jira_metrics_99thPercentile{name=\"webTemplateRenderer\",tag_templateRenderer=\"soy\"})"
    }
   ]
  },
  {
   "title": "Soy web panel render time (mean of last 5 minutes - cluster wide) ",
   "type": "timeseries",
   "description": "Measures how long a Soy Template web panel is taking to render.\n\nThe template renderer might be long running. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_entityType) ((com_atlassian_jira_metrics_Mean{name=\"webTemplateRenderer\",tag_templateRenderer=\"soy\"}) * \n(delta(com_atlassian_jira_metrics_Count{name=\"webTemplateRenderer\",tag_templateRenderer=\"soy\"}[5m])))) /\n(sum without (instance, tag_entityType) (delta(com_atlassian_jira_metrics_Count{name=\"webTemplateRenderer\",tag_templateRenderer=\"soy\"}[5m])))",
     "legendFormat": "{{ instance }} {{tag_fromPluginKey}} - {{tag_templateName}} (template)"
    }
   ]
  },
  {
   "title": "Soy web panel render time (p99 - per node) ",
   "type": "timeseries",
   "description": "Measures how long a Soy Template web panel is taking to render.\n\nThe template renderer might be long running. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_jira_metrics_99thPercentile{name=\"webTemplateRenderer\",tag_templateRenderer=\"soy\"}",
     "legendFormat": "{{tag_fromPluginKey}} - {{tag_templateName}}__{{instance}} (template)"
    }
   ]
  },
  { "title": "Web panel render times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Velocity web panel render times (cluster-wide)",
   "type": "table",
   "description": "Measures how long a Velocity template web panel is taking to render.\n\nThe template renderer might be long running. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "topk(500, avg without (instance, tag_templateName) (com_atlassian_jira_metrics_Mean{name=\"webTemplateRenderer\",tag_templateRenderer=\"velocity\"}) )"
    },
    {
     "expr": "sum without (instance, tag_templateName) (com_atlassian_jira_metrics_Count{name=\"webTemplateRenderer\",tag_templateRenderer=\"velocity\"})"
    },
    {
     "expr": "max without (instance, tag_templateName) (com_atlassian_jira_metrics_99thPercentile{name=\"webTemplateRenderer\",tag_templateRenderer=\"velocity\"})"
    }
   ]
  },
  {
   "title": "velocity web panel response time (mean of last 5 minutes - cluster wide) ",
   "type": "timeseries",
   "description": "Measures how long a Velocity template web panel is taking to render.\n\nThe template renderer might be long running. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance) ((com_atlassian_jira_metrics_Mean{name=\"webTemplateRenderer\",tag_templateRenderer=\"velocity\"}) * \n(delta(com_atlassian_jira_metrics_Count{name=\"webTemplateRenderer\",tag_templateRenderer=\"velocity\"}[5m])))) /\n(sum without (instance) (delta(com_atlassian_jira_metrics_Count{name=\"webTemplateRenderer\",tag_templateRenderer=\"velocity\"}[5m])))",
     "legendFormat": "{{ instance }} {{tag_fromPluginKey}} - {{tag_templateName}} (template)"
    }
   ]
  },
  {
   "title": "velocity web panel response time (p99 - per node) ",
   "type": "timeseries",
   "description": "Measures how long a Velocity template web panel is taking to render.\n\nThe template renderer might be long running. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, com_atlassian_jira_metrics_99thPercentile{name=\"webTemplateRenderer\",tag_templateRenderer=\"velocity\"})",
     "legendFormat": "{{ instance }} {{tag_fromPluginKey}} - {{tag_templateName}} (template)"
    }
   ]
  },
  { "title": "Web resource evaluation times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "web resource condition evaluation time (mean - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long web resource condition will take to determine whether a resource should be displayed or not.\n\nSlow web resource conditions lead to slow page load times especially if they are not cached. Reach out to the app vendor responsible to flag and investigate. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg without (instance) (com_atlassian_jira_metrics_Mean{category00=\"web\", category01=\"resource\", name=\"condition\"})",
     "legendFormat": "{{ instance }} {{tag_fromPluginKey}} - {{tag_conditionClassName}} (condition)"
    }
   ]
  },
  {
   "title": "web resource condition evaluation time (p99 - per node)",
   "type": "timeseries",
   "description": "Measures how long web resource condition will take to determine whether a resource should be displayed or not.\n\nSlow web resource conditions lead to slow page load times especially if they are not cached. Reach out to the app vendor responsible to flag and investigate. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, com_atlassian_jira_metrics_99thPercentile{category00=\"web\", category01=\"resource\", name=\"condition\"})",
     "legendFormat": "{{ instance }} {{tag_fromPluginKey}} - {{tag_conditionClassName}} (condition)"
    }
   ]
  },
  { "title": "REST response times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Most requested endpoints & response time",
   "type": "table",
   "description": "Use this table to quickly identify the slowest calls and some outliers using the 99th percentile response time. Use this table to figure out which endpoint to investigate then correlate it with the other timeseries panels for more detailed diagnosis ",
   "gridPos": { "h": 26, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "topk(500, avg without (instance) (com_atlassian_jira_metrics_Mean{category00=\"http\", category01=\"rest\", name=\"request\"}))"
    },
    {
     "expr": "sum without (instance) (com_atlassian_jira_metrics_Count{category00=\"http\", category01=\"rest\", name=\"request\"})"
    },
    {
     "expr": "max without (instance) (com_atlassian_jira_metrics_99thPercentile{category00=\"http\", category01=\"rest\", name=\"request\"})"
    }
   ]
  },
  {
   "title": "HTTP REST response time (mean of last 5 minutes - cluster wide)",
   "type": "timeseries",
   "description": "Measures HTTP responses of the REST APIs that uses the atlassian-rest module.\n\nCheck the frequency and duration of the rest requests. If excessive or very slow, consider reaching out to the app vendor and flag this issue to them.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_entityType) ((com_atlassian_jira_metrics_Mean{category00=\"http\", category01=\"rest\", name=\"request\"}) * \n(delta(com_atlassian_jira_metrics_Count{category00=\"http\", category01=\"rest\", name=\"request\"}[5m])))) /\n(sum without (instance, tag_entityType) (delta(com_atlassian_jira_metrics_Count{category00=\"http\", category01=\"rest\", name=\"request\"}[5m])))",
     "legendFormat": "{{ instance }} {{tag_fromPluginKey}} - {{tag_path}} (path)"
    }
   ]
  },
  {
   "title": "HTTP REST response time (p99 - per node)",
   "type": "timeseries",
   "description": "Measures HTTP response of the REST APIs that uses the atlassian-rest module.\n\nCheck the frequency and duration of the rest requests. If excessive or very slow, consider reaching out to the app vendor and flag this issue to the",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, com_atlassian_jira_metrics_99thPercentile{category00=\"http\", category01=\"rest\", name=\"request\"})",
     "legendFormat": "{{ instance }} {{tag_fromPluginKey}} - {{tag_path}} (path)"
    }
   ]
  },
  {
   "title": "HTTP REST average response time per plugin",
   "type": "timeseries",
   "description": "A timeseries of plugins REST average response times regardless of which node they are running on",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg without (instance, tag_path, tag_action) (com_atlassian_jira_metrics_Mean{category00=\"http\",category01=\"rest\", name=\"request\"})",
     "legendFormat": "{{ instance }} {{tag_fromPluginKey}}"
    }
   ]
  },
  { "title": "HTTP Requests via SAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "HTTP SAL request time (mean of last 5 minutes - cluster wide)",
   "type": "timeseries",
   "description": "Measures HTTP requests of the given unique URL that uses atlassian-sal module. \n\nCheck the frequency and duration of the http requests. If excessive or very slow, consider reaching out to the app vendor and flag this issue to them. You could also enable url optional tag to identify which urls are causing the issue, you can do so by setting a system variable like so atlassian.metrics.optional.tags.http.sal.request=url",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_action) ((com_atlassian_jira_metrics_Mean{category00=\"http\", category01=\"sal\", name=\"request\"}) * \n(delta(com_atlassian_jira_metrics_Count{category00=\"http\", category01=\"sal\", name=\"request\"}[5m])))) /\n(sum without (instance, tag_action) (delta(com_atlassian_jira_metrics_Count{category00=\"http\", category01=\"sal\", name=\"request\"}[5m])))\n",
     "legendFormat": "{{ instance }} {{tag_pluginKeyAtCreation}}"
    }
   ]
  },
  {
   "title": "HTTP SAL request time (p99 - per node)",
   "type": "timeseries",
   "description": "Measures HTTP requests of the given unique URL that uses atlassian-sal module. \n\nCheck the frequency and duration of the http requests. If excessive or very slow, consider reaching out to the app vendor and flag this issue to them. You could also enable url optional tag to identify which urls are causing the issue, you can do so by setting a system variable like so atlassian.metrics.optional.tags.http.sal.request=url",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, com_atlassian_jira_metrics_99thPercentile{category00=\"http\", category01=\"sal\", name=\"request\"})",
     "legendFormat": "{{ instance }} {{tag_pluginKeyAtCreation}}"
    }
   ]
  }
 ]
}