{
 "title": "Bitbucket Overview",
 "tags": [ "bitbucket" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "java_lang_Runtime_Pid{}", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{}/1000",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "java_lang_Runtime_StartTime{}", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Available CPU Cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Blocked Threads",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"BLOCKED\"}",
     "legendFormat": "{{ state }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(java_lang_G1_Old_Generation_CollectionTime{}[10m])",
     "legendFormat": "G1_Old_Generation ({{ instance }})"
    },
    {
     "expr": "increase(java_lang_G1_Young_Generation_CollectionTime{}[10m])",
     "legendFormat": "G1_Young_Generation ({{ instance }})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_ProcessCpuLoad{} * 100)",
     "legendFormat": "cpu load ({{ instance }})"
    }
   ]
  },
  {
   "title": "Heap Used %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(jvm_memory_bytes_used{area=\"heap\",}/jvm_memory_bytes_max{area=\"heap\",})",
     "legendFormat": "Used {{ area }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(java_lang_G1_Old_Generation_CollectionCount{}[10m])",
     "legendFormat": "G1_Old_Generation ({{ instance }})"
    },
    {
     "expr": "increase(java_lang_G1_Young_Generation_CollectionCount{}[10m])",
     "legendFormat": "G1_Young_Generation ({{ instance }})"
    }
   ]
  },
  {
   "title": "Request Processing Time",
   "type": "timeseries",
   "description": "Rest request processing time by plugin, method and path",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_bitbucket_metrics_Mean{category00=\"http\",category01=\"rest\",name=\"request\"}",
     "legendFormat": "{{ tag_action }}: {{tag_fromPluginKey}} on {{ tag_path }}"
    }
   ]
  },
  {
   "title": "Hikari Pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_zaxxer_hikari_Pool_bitbucket_IdleConnections{}",
     "legendFormat": "idle ({{instance}})"
    },
    {
     "expr": "com_zaxxer_hikari_Pool_bitbucket_ActiveConnections{}",
     "legendFormat": "active ({{instance}})"
    },
    {
     "expr": "com_zaxxer_hikari_Pool_bitbucket_ThreadsAwaitingConnection",
     "legendFormat": "awaiting ({{instance}})"
    },
    {
     "expr": "com_zaxxer_hikari_Pool_bitbucket_TotalConnections",
     "legendFormat": "total ({{instance}})"
    }
   ]
  },
  {
   "title": "Hibernate Cached Requests",
   "type": "timeseries",
   "description": "Global number of cached queries successfully retrieved or missed from cache",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "org_hibernate_core_bitbucket_core_QueryCacheHitCount{serviceRole=\"org.hibernate.stat.Statistics\",serviceType=\"org.hibernate.stat.internal.StatisticsImpl\",}",
     "legendFormat": "retrieved from cache ({{ instance }})"
    },
    {
     "expr": "org_hibernate_core_bitbucket_core_QueryCacheMissCount{serviceRole=\"org.hibernate.stat.Statistics\",serviceType=\"org.hibernate.stat.internal.StatisticsImpl\"}",
     "legendFormat": "not found in cache ({{ instance }})"
    }
   ]
  },
  {
   "title": "Hibernate Cached Entities",
   "type": "timeseries",
   "description": "Global number of cacheable entities/collections successfully retrieved from the cache or not found in cache and loaded from the database",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "org_hibernate_core_bitbucket_core_SecondLevelCacheHitCount{serviceRole=\"org.hibernate.stat.Statistics\",serviceType=\"org.hibernate.stat.internal.StatisticsImpl\"}",
     "legendFormat": "retrieved from cache ({{ instance }})"
    },
    {
     "expr": "org_hibernate_core_bitbucket_core_SecondLevelCacheMissCount{serviceRole=\"org.hibernate.stat.Statistics\",serviceType=\"org.hibernate.stat.internal.StatisticsImpl\"}",
     "legendFormat": "not found in cache ({{ instance }})"
    }
   ]
  }
 ]
}